---
version: '3'
services:
  postgres:
    image: postgres:14.3
    container_name: movies-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testingjava
      - POSTGRES_DB=movies
    volumes:
      - ./PostgreSQLSchema.sql:/docker-entrypoint-initdb.d/init.sql
